/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.SubVentanas;

import Modelos.Trabajo;
import Principal.Principal;

/**
 *
 * @author Frank
 */
public class MostrarTrabajosPublicosEmpleador extends javax.swing.JFrame {

    /**
     * Creates new form MostrarTrabajosPublicosEmpleador
     */
    public MostrarTrabajosPublicosEmpleador() {
        initComponents();
        setBounds(400, 200, 435, 380);
        mostrarTrabajosPublicados();
    }

    private void mostrarTrabajosPublicados() {
        Principal prin = new Principal();
        String Mensage = "";
        boolean con = true;
        int cod = 0;
        for (Trabajo T : prin.getTrabajo()) {
            if (T.getPublicador().equalsIgnoreCase(prin.getEmpleador().get(prin.getPosActiv()).getNombre())) {
                Mensage += ("Personal: " + T.getPersonal() + "\t[" + T.getCantidad() + "]" + "\nPara la empresa: " + T.getEmpresa() + "\tCod:\t"+cod+"\n\n");
                con = false;
            }
            cod++;
        }
        if (con) {
            jTextArea1.setText("Usted Aun no a publicado ninguna oportunidad de empleo");
        }
        jTextArea1.setText(Mensage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 52, 400, 240);

        jButtonOk.setBackground(new java.awt.Color(204, 204, 255));
        jButtonOk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonOk.setForeground(new java.awt.Color(0, 0, 255));
        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOk);
        jButtonOk.setBounds(363, 306, 50, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 16, 208));
        jLabel1.setText("TRABAJOS PUBLICADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(142, 11, 179, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Abstracto_380pA.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        this.setVisible(false);
        this.dispose();
        new Principal().getVentCuentEmp().setVisible(true);
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
