/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Modelos.Trabajo;
import Ventanas.SubVentanas.EliminarTrabajo;
import Ventanas.SubVentanas.MostrarTrabajo;
import Ventanas.SubVentanas.MostrarTrabajosPublicosEmpleador;
import static Ventanas.inicio.prin;
import javax.swing.JTextField;

/**
 *
 * @author Frank
 */
public class CuentaEmpleador extends javax.swing.JFrame {

    /**
     * Creates new form CuentaEmpleador
     */
    public CuentaEmpleador() {
        initComponents();
        ActualizarInfoUsuario();
        MostrarPublicaciones();
        this.setBounds(360, 200, 630, 440);
    }

    private void ActualizarInfoUsuario() {
        this.jLabelNickUsuario.setText(prin.getEmpleador().get(prin.getPosActiv()).getNick());
        this.jLabelOcupacionMesage.setText("Empresa:");
        this.jLabelOcupacion.setText(prin.getEmpleador().get(prin.getPosActiv()).getEmpresa());

    }

    private void MostrarPublicaciones() {
        String Mensage = "";
        boolean con = true;
        int cod = 0;
        for (Trabajo T : prin.getTrabajo()) {
            if (T.getPublicador().equalsIgnoreCase(prin.getEmpleador().get(prin.getPosActiv()).getNombre())) {
                Mensage += ("Personal: " + T.getPersonal() + "\t[" + T.getCantidad() + "]" + "\nPara la empresa: " + T.getEmpresa() + "\tCod:\t" + cod + "\n\n");
                con = false;
            }
            cod++;
        }
        if (con) {
            this.jTextPaneTrabajosPublicados.setText("Usted no a publicado ningun trabajo todabia");
            return;
        } else {
            this.jTextPaneTrabajosPublicados.setText(Mensage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor .
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextFieldBusqueda = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneTrabajosPublicados = new javax.swing.JTextPane();
        jButtonEditarPerfil = new javax.swing.JButton();
        jButtonAgregarTrabajo = new javax.swing.JButton();
        jButtonEliminarTrabajo = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelNickUsuario = new javax.swing.JLabel();
        jLabelOcupacionMesage = new javax.swing.JLabel();
        jLabelOcupacion = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();
        jLabelMenBuscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuopciones = new javax.swing.JMenu();
        jMenuItemOpcionesCerrarSesion = new javax.swing.JMenuItem();
        jMenuItemOpcionesEditarPerfil = new javax.swing.JMenuItem();
        jMenuIr = new javax.swing.JMenu();
        jMenuItemIrInicio = new javax.swing.JMenuItem();
        jMenuItemIrCuenta = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jMenuItemVerEmpresas = new javax.swing.JMenuItem();
        jMenuItemVerNotificaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta");
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(JTextFieldBusqueda);
        JTextFieldBusqueda.setBounds(370, 270, 210, 31);

        jButtonBuscar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(480, 310, 100, 30);

        jTextPaneTrabajosPublicados.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneTrabajosPublicados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 138, 184, 197);

        jButtonEditarPerfil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonEditarPerfil.setText("Editar Perfil");
        jButtonEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarPerfil);
        jButtonEditarPerfil.setBounds(290, 30, 128, 90);

        jButtonAgregarTrabajo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAgregarTrabajo.setText("Agregar Trabajo");
        jButtonAgregarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarTrabajo);
        jButtonAgregarTrabajo.setBounds(450, 30, 130, 90);

        jButtonEliminarTrabajo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonEliminarTrabajo.setText("Eliminar");
        jButtonEliminarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarTrabajo);
        jButtonEliminarTrabajo.setBounds(290, 150, 128, 88);

        jButtonMostrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrar);
        jButtonMostrar.setBounds(450, 150, 130, 88);

        jPanelUsuario.setBackground(new java.awt.Color(204, 204, 204));

        jLabelNickUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNickUsuario.setForeground(new java.awt.Color(0, 51, 255));
        jLabelNickUsuario.setText("rrrrrrr");

        jLabelOcupacionMesage.setForeground(new java.awt.Color(0, 0, 255));
        jLabelOcupacionMesage.setText("Ocupacion:");

        jLabelOcupacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelOcupacion.setForeground(new java.awt.Color(0, 51, 255));
        jLabelOcupacion.setText("kkkkkk");

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelNickUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelOcupacionMesage, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNickUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOcupacionMesage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanelUsuario);
        jPanelUsuario.setBounds(80, 11, 161, 110);

        jButtonActualizar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(0, 0, 204));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonActualizar);
        jButtonActualizar.setBounds(154, 341, 110, 30);
        getContentPane().add(jLabelMenBuscar);
        jLabelMenBuscar.setBounds(282, 286, 195, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Fondo_UsEmpleador_640p.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 390);

        jMenuBarPrincipal.setBackground(new java.awt.Color(1, 213, 255));

        jMenuopciones.setText("Opciones");

        jMenuItemOpcionesCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Out_25p.png"))); // NOI18N
        jMenuItemOpcionesCerrarSesion.setText("Cerrar sesion");
        jMenuItemOpcionesCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpcionesCerrarSesionActionPerformed(evt);
            }
        });
        jMenuopciones.add(jMenuItemOpcionesCerrarSesion);

        jMenuItemOpcionesEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Settings_25p.png"))); // NOI18N
        jMenuItemOpcionesEditarPerfil.setText("Editar perfil");
        jMenuItemOpcionesEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpcionesEditarPerfilActionPerformed(evt);
            }
        });
        jMenuopciones.add(jMenuItemOpcionesEditarPerfil);

        jMenuBarPrincipal.add(jMenuopciones);

        jMenuIr.setText("Ir");

        jMenuItemIrInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/home_25p.png"))); // NOI18N
        jMenuItemIrInicio.setText("Inicio");
        jMenuItemIrInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIrInicioActionPerformed(evt);
            }
        });
        jMenuIr.add(jMenuItemIrInicio);

        jMenuItemIrCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/User-icon_25p.png"))); // NOI18N
        jMenuItemIrCuenta.setText("Cuenta");
        jMenuItemIrCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIrCuentaActionPerformed(evt);
            }
        });
        jMenuIr.add(jMenuItemIrCuenta);

        jMenuBarPrincipal.add(jMenuIr);

        jMenuVer.setText("Ver");

        jMenuItemVerEmpresas.setText("Empresas");
        jMenuVer.add(jMenuItemVerEmpresas);

        jMenuItemVerNotificaciones.setText("Notificaciones");
        jMenuVer.add(jMenuItemVerNotificaciones);

        jMenuBarPrincipal.add(jMenuVer);

        setJMenuBar(jMenuBarPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTrabajoActionPerformed
        prin.getVentCuentEmp().setVisible(false);
        new FormularioDeTrabajo().show(true);
    }//GEN-LAST:event_jButtonAgregarTrabajoActionPerformed

    private void jMenuItemOpcionesCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpcionesCerrarSesionActionPerformed
        prin.getVentCuentEmp().setVisible(false);
        prin.cerrarCesionVentanas();
    }//GEN-LAST:event_jMenuItemOpcionesCerrarSesionActionPerformed

    private void jMenuItemOpcionesEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpcionesEditarPerfilActionPerformed
        prin.getVentCuentEmp().setVisible(false);
        int op = 1;
        new EditarPerfil(op).show(true);
    }//GEN-LAST:event_jMenuItemOpcionesEditarPerfilActionPerformed

    private void jMenuItemIrInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIrInicioActionPerformed
        prin.getVentCuentEmp().setVisible(false);
        prin.getVentPrinci().setVisible(true);
    }//GEN-LAST:event_jMenuItemIrInicioActionPerformed

    private void jMenuItemIrCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIrCuentaActionPerformed
        return;
    }//GEN-LAST:event_jMenuItemIrCuentaActionPerformed

    private void jButtonEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarPerfilActionPerformed
        prin.getVentCuentEmp().setVisible(false);
        int op = 1;
        new EditarPerfil(op).show(true);
    }//GEN-LAST:event_jButtonEditarPerfilActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        prin.getVentCuentEmp().setVisible(false);
        new MostrarTrabajosPublicosEmpleador().show(true);
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonEliminarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTrabajoActionPerformed
        this.setVisible(false);
        new EliminarTrabajo().show(true);
    }//GEN-LAST:event_jButtonEliminarTrabajoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        ActualizarInfoUsuario();
        MostrarPublicaciones();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String cod = "" + JTextFieldBusqueda.getText();
        if (cod.equalsIgnoreCase("")) {
            jLabelMenBuscar.setText("Primero ingrese el Cod. a buscar");
            return;
        } else {
            int n = 0;
            try {
                n = Integer.parseInt(cod);
            } catch (Exception e) {
                jLabelMenBuscar.setText("Codigo Incorrecto");
                return;
            }
            if (prin.getTrabajo().size() <= n || n < 0) {
                jLabelMenBuscar.setText("Codigo Incorrecto");
                return;
            }
            prin.getVentCuentEmp().setVisible(false);
            jLabelMenBuscar.setText("");
            new MostrarTrabajo(n, 1).show();
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldBusqueda;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregarTrabajo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditarPerfil;
    private javax.swing.JButton jButtonEliminarTrabajo;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMenBuscar;
    private javax.swing.JLabel jLabelNickUsuario;
    private javax.swing.JLabel jLabelOcupacion;
    private javax.swing.JLabel jLabelOcupacionMesage;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuIr;
    private javax.swing.JMenuItem jMenuItemIrCuenta;
    private javax.swing.JMenuItem jMenuItemIrInicio;
    private javax.swing.JMenuItem jMenuItemOpcionesCerrarSesion;
    private javax.swing.JMenuItem jMenuItemOpcionesEditarPerfil;
    private javax.swing.JMenuItem jMenuItemVerEmpresas;
    private javax.swing.JMenuItem jMenuItemVerNotificaciones;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JMenu jMenuopciones;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneTrabajosPublicados;
    // End of variables declaration//GEN-END:variables
}
